apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-static-web-dev
  labels:
    app: simple-static-web-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-static-web-dev
  template:
    metadata:
      labels:
        app: simple-static-web-dev
    spec:
      containers:
        - name: simple-static-web-dev
          image: 10.10.10.116:8083/simple-static-web:1.0.18
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
