apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-static-web-dev
  namespace: dev-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-static-web
  template:
    metadata:
      labels:
        app: simple-static-web
    spec:
      containers:
        - name: simple-static-web-dev
          image: 10.10.10.116:8083/simple-static-web:1.0.30
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: nexus-registry-secret
