apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-static-web-dev
  labels:
        app: simple-static-web
  namespace: dev-web   # optional, if you want it in dev-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-static-web
  template:
    metadata:
      labels:
        app: simple-static-web
    spec:   # 👈 only one 'spec' under 'template'
      imagePullSecrets:
        - name: nexus-registry-secret	
      containers:
        - name: simple-static-web
          image: 10.10.10.116:8083/simple-static-web:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
