apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-static-web-dev
  namespace: dev-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-static-web-dev
  template:
    metadata:
      labels:
        app: simple-static-web-dev
    spec:
      containers:
        - name: simple-static-web
          image: simple-static-web:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
