apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-web
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: 'https://github.com/gokulbanik/rancher.git'   # <-- replace with your real repo URL
    targetRevision: main
    path: simple-static-web-deployment/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev-web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
