apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.serviceName }}
  labels:
    app: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  sessionAffinity: {{ .Values.service.sessionAffinity | default "None" }}
