apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-static-web.fullname" . }}
  labels:
    {{- include "simple-static-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "simple-static-web.name" . }}
