apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret-dev
  namespace: dev-web
type: Opaque
data:
  # The value should be the base64-encoded content of your .htpasswd file cat /tmp/auth | base64 -w 0
  auth: {{aHR1c2VyOiRhcHIxJGlubFUvV1hnJFN0T3NkMjJGRFV5aGNtcTB4MGlSZjEK}}
