replicaCount: 1

image:
  repository: simple-static-web
  tag: 1.0.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
#  - name: nexus-registry-secret

app:
  name: simple-static-web
  serviceName: simple-static-web-svc

service:
  type: ClusterIP 
  port: 80
  nodePort: 30080  # Optional: specify a NodePort
  sessionAffinity: None

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

httpRoute:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
