replicaCount: 1

image:
  repository: docker.io/library/simple-static-web:1.0.1
  tag: 1.0.1
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: nexus-registry-secret

service:
  type: NodePort
  port: 80
  nodePort: 30080  # Optional: specify a NodePort

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

httpRoute:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
